// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package org.liang.protoc;

public final class MachineBookProtos {
  private MachineBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MachineOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string hostName = 1;
    /**
     * <code>required string hostName = 1;</code>
     */
    boolean hasHostName();
    /**
     * <code>required string hostName = 1;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>required string hostName = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    // required int32 port = 2;
    /**
     * <code>required int32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 2;</code>
     */
    int getPort();

    // required int32 id = 3;
    /**
     * <code>required int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 3;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code protoc.Machine}
   */
  public static final class Machine extends
      com.google.protobuf.GeneratedMessage
      implements MachineOrBuilder {
    // Use Machine.newBuilder() to construct.
    private Machine(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Machine(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Machine defaultInstance;
    public static Machine getDefaultInstance() {
      return defaultInstance;
    }

    public Machine getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Machine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hostName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.liang.protoc.MachineBookProtos.internal_static_protoc_Machine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.liang.protoc.MachineBookProtos.internal_static_protoc_Machine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.liang.protoc.MachineBookProtos.Machine.class, org.liang.protoc.MachineBookProtos.Machine.Builder.class);
    }

    public static com.google.protobuf.Parser<Machine> PARSER =
        new com.google.protobuf.AbstractParser<Machine>() {
      public Machine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Machine(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Machine> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protoc.Machine.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.liang.protoc.MachineBookProtos.Machine.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protoc.Machine.PhoneType)
    }

    private int bitField0_;
    // required string hostName = 1;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object hostName_;
    /**
     * <code>required string hostName = 1;</code>
     */
    public boolean hasHostName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string hostName = 1;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hostName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required int32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    // required int32 id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>required int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      hostName_ = "";
      port_ = 0;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHostName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.Machine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.liang.protoc.MachineBookProtos.Machine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.Machine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.liang.protoc.MachineBookProtos.MachineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_Machine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_Machine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.liang.protoc.MachineBookProtos.Machine.class, org.liang.protoc.MachineBookProtos.Machine.Builder.class);
      }

      // Construct using org.liang.protoc.MachineBookProtos.Machine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hostName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_Machine_descriptor;
      }

      public org.liang.protoc.MachineBookProtos.Machine getDefaultInstanceForType() {
        return org.liang.protoc.MachineBookProtos.Machine.getDefaultInstance();
      }

      public org.liang.protoc.MachineBookProtos.Machine build() {
        org.liang.protoc.MachineBookProtos.Machine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.liang.protoc.MachineBookProtos.Machine buildPartial() {
        org.liang.protoc.MachineBookProtos.Machine result = new org.liang.protoc.MachineBookProtos.Machine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostName_ = hostName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.liang.protoc.MachineBookProtos.Machine) {
          return mergeFrom((org.liang.protoc.MachineBookProtos.Machine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.liang.protoc.MachineBookProtos.Machine other) {
        if (other == org.liang.protoc.MachineBookProtos.Machine.getDefaultInstance()) return this;
        if (other.hasHostName()) {
          bitField0_ |= 0x00000001;
          hostName_ = other.hostName_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHostName()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.liang.protoc.MachineBookProtos.Machine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.liang.protoc.MachineBookProtos.Machine) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string hostName = 1;
      private java.lang.Object hostName_ = "";
      /**
       * <code>required string hostName = 1;</code>
       */
      public boolean hasHostName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string hostName = 1;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hostName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hostName = 1;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hostName = 1;</code>
       */
      public Builder clearHostName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>required string hostName = 1;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostName_ = value;
        onChanged();
        return this;
      }

      // required int32 port = 2;
      private int port_ ;
      /**
       * <code>required int32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      // required int32 id = 3;
      private int id_ ;
      /**
       * <code>required int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoc.Machine)
    }

    static {
      defaultInstance = new Machine(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.Machine)
  }

  public interface MachineBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protoc.Machine machine = 5;
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    java.util.List<org.liang.protoc.MachineBookProtos.Machine> 
        getMachineList();
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    org.liang.protoc.MachineBookProtos.Machine getMachine(int index);
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    int getMachineCount();
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    java.util.List<? extends org.liang.protoc.MachineBookProtos.MachineOrBuilder> 
        getMachineOrBuilderList();
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    org.liang.protoc.MachineBookProtos.MachineOrBuilder getMachineOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoc.MachineBook}
   */
  public static final class MachineBook extends
      com.google.protobuf.GeneratedMessage
      implements MachineBookOrBuilder {
    // Use MachineBook.newBuilder() to construct.
    private MachineBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MachineBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MachineBook defaultInstance;
    public static MachineBook getDefaultInstance() {
      return defaultInstance;
    }

    public MachineBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MachineBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                machine_ = new java.util.ArrayList<org.liang.protoc.MachineBookProtos.Machine>();
                mutable_bitField0_ |= 0x00000001;
              }
              machine_.add(input.readMessage(org.liang.protoc.MachineBookProtos.Machine.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          machine_ = java.util.Collections.unmodifiableList(machine_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.liang.protoc.MachineBookProtos.internal_static_protoc_MachineBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.liang.protoc.MachineBookProtos.internal_static_protoc_MachineBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.liang.protoc.MachineBookProtos.MachineBook.class, org.liang.protoc.MachineBookProtos.MachineBook.Builder.class);
    }

    public static com.google.protobuf.Parser<MachineBook> PARSER =
        new com.google.protobuf.AbstractParser<MachineBook>() {
      public MachineBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MachineBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MachineBook> getParserForType() {
      return PARSER;
    }

    // repeated .protoc.Machine machine = 5;
    public static final int MACHINE_FIELD_NUMBER = 5;
    private java.util.List<org.liang.protoc.MachineBookProtos.Machine> machine_;
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    public java.util.List<org.liang.protoc.MachineBookProtos.Machine> getMachineList() {
      return machine_;
    }
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    public java.util.List<? extends org.liang.protoc.MachineBookProtos.MachineOrBuilder> 
        getMachineOrBuilderList() {
      return machine_;
    }
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    public int getMachineCount() {
      return machine_.size();
    }
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    public org.liang.protoc.MachineBookProtos.Machine getMachine(int index) {
      return machine_.get(index);
    }
    /**
     * <code>repeated .protoc.Machine machine = 5;</code>
     */
    public org.liang.protoc.MachineBookProtos.MachineOrBuilder getMachineOrBuilder(
        int index) {
      return machine_.get(index);
    }

    private void initFields() {
      machine_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMachineCount(); i++) {
        if (!getMachine(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < machine_.size(); i++) {
        output.writeMessage(5, machine_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < machine_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, machine_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.liang.protoc.MachineBookProtos.MachineBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.liang.protoc.MachineBookProtos.MachineBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoc.MachineBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.liang.protoc.MachineBookProtos.MachineBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_MachineBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_MachineBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.liang.protoc.MachineBookProtos.MachineBook.class, org.liang.protoc.MachineBookProtos.MachineBook.Builder.class);
      }

      // Construct using org.liang.protoc.MachineBookProtos.MachineBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMachineFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (machineBuilder_ == null) {
          machine_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          machineBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.liang.protoc.MachineBookProtos.internal_static_protoc_MachineBook_descriptor;
      }

      public org.liang.protoc.MachineBookProtos.MachineBook getDefaultInstanceForType() {
        return org.liang.protoc.MachineBookProtos.MachineBook.getDefaultInstance();
      }

      public org.liang.protoc.MachineBookProtos.MachineBook build() {
        org.liang.protoc.MachineBookProtos.MachineBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.liang.protoc.MachineBookProtos.MachineBook buildPartial() {
        org.liang.protoc.MachineBookProtos.MachineBook result = new org.liang.protoc.MachineBookProtos.MachineBook(this);
        int from_bitField0_ = bitField0_;
        if (machineBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            machine_ = java.util.Collections.unmodifiableList(machine_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.machine_ = machine_;
        } else {
          result.machine_ = machineBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.liang.protoc.MachineBookProtos.MachineBook) {
          return mergeFrom((org.liang.protoc.MachineBookProtos.MachineBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.liang.protoc.MachineBookProtos.MachineBook other) {
        if (other == org.liang.protoc.MachineBookProtos.MachineBook.getDefaultInstance()) return this;
        if (machineBuilder_ == null) {
          if (!other.machine_.isEmpty()) {
            if (machine_.isEmpty()) {
              machine_ = other.machine_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMachineIsMutable();
              machine_.addAll(other.machine_);
            }
            onChanged();
          }
        } else {
          if (!other.machine_.isEmpty()) {
            if (machineBuilder_.isEmpty()) {
              machineBuilder_.dispose();
              machineBuilder_ = null;
              machine_ = other.machine_;
              bitField0_ = (bitField0_ & ~0x00000001);
              machineBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMachineFieldBuilder() : null;
            } else {
              machineBuilder_.addAllMessages(other.machine_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMachineCount(); i++) {
          if (!getMachine(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.liang.protoc.MachineBookProtos.MachineBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.liang.protoc.MachineBookProtos.MachineBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protoc.Machine machine = 5;
      private java.util.List<org.liang.protoc.MachineBookProtos.Machine> machine_ =
        java.util.Collections.emptyList();
      private void ensureMachineIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          machine_ = new java.util.ArrayList<org.liang.protoc.MachineBookProtos.Machine>(machine_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.liang.protoc.MachineBookProtos.Machine, org.liang.protoc.MachineBookProtos.Machine.Builder, org.liang.protoc.MachineBookProtos.MachineOrBuilder> machineBuilder_;

      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public java.util.List<org.liang.protoc.MachineBookProtos.Machine> getMachineList() {
        if (machineBuilder_ == null) {
          return java.util.Collections.unmodifiableList(machine_);
        } else {
          return machineBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public int getMachineCount() {
        if (machineBuilder_ == null) {
          return machine_.size();
        } else {
          return machineBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public org.liang.protoc.MachineBookProtos.Machine getMachine(int index) {
        if (machineBuilder_ == null) {
          return machine_.get(index);
        } else {
          return machineBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder setMachine(
          int index, org.liang.protoc.MachineBookProtos.Machine value) {
        if (machineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachineIsMutable();
          machine_.set(index, value);
          onChanged();
        } else {
          machineBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder setMachine(
          int index, org.liang.protoc.MachineBookProtos.Machine.Builder builderForValue) {
        if (machineBuilder_ == null) {
          ensureMachineIsMutable();
          machine_.set(index, builderForValue.build());
          onChanged();
        } else {
          machineBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder addMachine(org.liang.protoc.MachineBookProtos.Machine value) {
        if (machineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachineIsMutable();
          machine_.add(value);
          onChanged();
        } else {
          machineBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder addMachine(
          int index, org.liang.protoc.MachineBookProtos.Machine value) {
        if (machineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachineIsMutable();
          machine_.add(index, value);
          onChanged();
        } else {
          machineBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder addMachine(
          org.liang.protoc.MachineBookProtos.Machine.Builder builderForValue) {
        if (machineBuilder_ == null) {
          ensureMachineIsMutable();
          machine_.add(builderForValue.build());
          onChanged();
        } else {
          machineBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder addMachine(
          int index, org.liang.protoc.MachineBookProtos.Machine.Builder builderForValue) {
        if (machineBuilder_ == null) {
          ensureMachineIsMutable();
          machine_.add(index, builderForValue.build());
          onChanged();
        } else {
          machineBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder addAllMachine(
          java.lang.Iterable<? extends org.liang.protoc.MachineBookProtos.Machine> values) {
        if (machineBuilder_ == null) {
          ensureMachineIsMutable();
          super.addAll(values, machine_);
          onChanged();
        } else {
          machineBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder clearMachine() {
        if (machineBuilder_ == null) {
          machine_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          machineBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public Builder removeMachine(int index) {
        if (machineBuilder_ == null) {
          ensureMachineIsMutable();
          machine_.remove(index);
          onChanged();
        } else {
          machineBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public org.liang.protoc.MachineBookProtos.Machine.Builder getMachineBuilder(
          int index) {
        return getMachineFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public org.liang.protoc.MachineBookProtos.MachineOrBuilder getMachineOrBuilder(
          int index) {
        if (machineBuilder_ == null) {
          return machine_.get(index);  } else {
          return machineBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public java.util.List<? extends org.liang.protoc.MachineBookProtos.MachineOrBuilder> 
           getMachineOrBuilderList() {
        if (machineBuilder_ != null) {
          return machineBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(machine_);
        }
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public org.liang.protoc.MachineBookProtos.Machine.Builder addMachineBuilder() {
        return getMachineFieldBuilder().addBuilder(
            org.liang.protoc.MachineBookProtos.Machine.getDefaultInstance());
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public org.liang.protoc.MachineBookProtos.Machine.Builder addMachineBuilder(
          int index) {
        return getMachineFieldBuilder().addBuilder(
            index, org.liang.protoc.MachineBookProtos.Machine.getDefaultInstance());
      }
      /**
       * <code>repeated .protoc.Machine machine = 5;</code>
       */
      public java.util.List<org.liang.protoc.MachineBookProtos.Machine.Builder> 
           getMachineBuilderList() {
        return getMachineFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.liang.protoc.MachineBookProtos.Machine, org.liang.protoc.MachineBookProtos.Machine.Builder, org.liang.protoc.MachineBookProtos.MachineOrBuilder> 
          getMachineFieldBuilder() {
        if (machineBuilder_ == null) {
          machineBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.liang.protoc.MachineBookProtos.Machine, org.liang.protoc.MachineBookProtos.Machine.Builder, org.liang.protoc.MachineBookProtos.MachineOrBuilder>(
                  machine_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          machine_ = null;
        }
        return machineBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protoc.MachineBook)
    }

    static {
      defaultInstance = new MachineBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoc.MachineBook)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_Machine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_Machine_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoc_MachineBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoc_MachineBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\006protoc\"b\n\007Machine\022\020\n\010ho" +
      "stName\030\001 \002(\t\022\014\n\004port\030\002 \002(\005\022\n\n\002id\030\003 \002(\005\"+" +
      "\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WOR" +
      "K\020\002\"/\n\013MachineBook\022 \n\007machine\030\005 \003(\0132\017.pr" +
      "otoc.MachineB%\n\020org.liang.protocB\021Machin" +
      "eBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoc_Machine_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoc_Machine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_Machine_descriptor,
              new java.lang.String[] { "HostName", "Port", "Id", });
          internal_static_protoc_MachineBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoc_MachineBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoc_MachineBook_descriptor,
              new java.lang.String[] { "Machine", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
